env:
  browser: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules: { "prettier/prettier": "error" }
plugins: ["prettier"]
